recipe: default.v1
language: en
pipeline:
- name: MultiStepLLMCommandGenerator
  llm:
    model_name: gpt-4

policies:
- name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy
assistant_id: 20240917-052515-lead-out
